# Generated by Django 5.2.17 on 2026-09-09 06:56

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorGroup',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('YARD_OWNER', 'Yard owner'), ('FLEET', 'Fleet'), ('SACCO', 'SACCO'), ('PARTNERSHIP', 'Partnership')], max_length=16)),
                ('standing', models.CharField(choices=[('GOOD', 'Good'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended')], default='GOOD', max_length=16)),
                ('assignment_mode', models.CharField(choices=[('MANAGER_ASSIGNS', 'Manager assigns'), ('DRIVER_ACCEPTS', 'Driver accepts')], default='MANAGER_ASSIGNS', max_length=20)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=16)),
            ],
            options={
                'db_table': 'operator_group',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('DRIVER', 'Driver')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_membership',
            },
        ),
    ]
