# Generated by Django 5.2.17 on 2026-09-09 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='operators.operatorprofile'),
        ),
        migrations.AddField(
            model_name='operatorgroup',
            name='primary_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_contact_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.operatorgroup'),
        ),
        migrations.AddIndex(
            model_name='operatorgroup',
            index=models.Index(fields=['standing'], name='operator_gr_standin_4a6e20_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'role', 'status'], name='group_membe_group_i_eabbc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'operator'), name='uniq_group_member'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('operator',), name='uniq_active_group_per_operator'),
        ),
    ]
