# Generated by Django 5.2.17 on 2026-09-09 12:21

import django.contrib.postgres.fields
import django.db.models.deletion
import fikisha.common.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('operators', '0001_initial'),
        ('platform_config', '0005_seed_vehicle_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_descriptor', models.CharField(blank=True, default='', max_length=80)),
                ('registration', models.CharField(max_length=32)),
                ('registration_normalized', models.CharField(db_index=True, editable=False, max_length=32)),
                ('make', models.CharField(blank=True, default='', max_length=60)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('capacity_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity_unit', models.CharField(choices=[('KG', 'Kilograms'), ('TONNES', 'Tonnes')], default='KG', max_length=8)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tare_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('ownership', models.CharField(choices=[('OWNED', 'Owned'), ('AUTHORISED_DRIVER', 'Authorised driver')], default='OWNED', max_length=20)),
                ('speed_limiter_fitted', models.BooleanField(blank=True, null=True)),
                ('telematics_installed', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_REPAIR', 'Under repair'), ('SUSPENDED', 'Suspended')], default='INACTIVE', max_length=16)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('owner_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='groups.operatorgroup')),
                ('owner_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='operators.operatorprofile')),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_config.vehicleclass')),
            ],
            options={
                'db_table': 'vehicle',
                'indexes': [models.Index(fields=['owner_operator', 'status'], name='vehicle_owner_o_2bab7f_idx'), models.Index(fields=['owner_group', 'status'], name='vehicle_owner_g_2bc6ea_idx'), models.Index(fields=['vehicle_class'], name='vehicle_vehicle_042577_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('owner_group__isnull', True), ('owner_operator__isnull', False)), models.Q(('owner_group__isnull', False), ('owner_operator__isnull', True)), _connector='OR'), name='vehicle_exactly_one_controller'), models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True)), fields=('registration_normalized',), name='uniq_active_vehicle_registration')],
            },
        ),
    ]
