# Generated by Django 5.2.17 on 2026-09-09 06:56

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_config', '0002_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trading_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('standing', models.CharField(choices=[('GOOD', 'Good'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended')], default='GOOD', max_length=16)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=16)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_account',
            },
        ),
        migrations.CreateModel(
            name='BusinessLocation',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('MAIN', 'Main'), ('BRANCH', 'Branch'), ('WAREHOUSE', 'Warehouse'), ('STORE', 'Store'), ('PICKUP_POINT', 'Pickup point')], max_length=16)),
                ('address_text', models.TextField(blank=True, default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('access_notes', models.TextField(blank=True, default='')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='business.businessaccount')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_config.zone')),
            ],
            options={
                'db_table': 'business_location',
            },
        ),
        migrations.CreateModel(
            name='BusinessMembership',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('DISPATCHER', 'Dispatcher'), ('VIEWER', 'Viewer')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='business.businessaccount')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_membership',
            },
        ),
        migrations.AddIndex(
            model_name='businessaccount',
            index=models.Index(fields=['owner_user'], name='business_ac_owner_u_809743_idx'),
        ),
        migrations.AddIndex(
            model_name='businessaccount',
            index=models.Index(fields=['standing'], name='business_ac_standin_a3d9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslocation',
            index=models.Index(condition=models.Q(('deactivated_at__isnull', True)), fields=['business'], name='ix_active_business_location'),
        ),
        migrations.AddConstraint(
            model_name='businesslocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deactivated_at__isnull', True), ('type', 'MAIN')), fields=('business',), name='uniq_main_location_per_business'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['business', 'status'], name='business_me_busines_84b6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmembership',
            index=models.Index(fields=['user', 'status'], name='business_me_user_id_636279_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessmembership',
            constraint=models.UniqueConstraint(fields=('business', 'user'), name='uniq_business_member'),
        ),
    ]
