# Generated by Django 5.2.17 on 2026-09-09 12:21

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('operators', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDecision',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('START_REVIEW', 'Start review'), ('REQUEST_INFO', 'Request info'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('EXPIRE', 'Expire (system)'), ('RENEW', 'Renew')], max_length=16)),
                ('actor_role', models.CharField(blank=True, default='', max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('set_expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_decision',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('OPERATOR', 'Operator'), ('VEHICLE', 'Vehicle'), ('BASE', 'Operating location')], max_length=12)),
                ('domain', models.CharField(choices=[('IDENTITY', 'Identity'), ('LICENCE', 'Driving licence'), ('GOOD_CONDUCT', 'Certificate of Good Conduct'), ('VEHICLE', 'Vehicle (registration / roadworthiness)'), ('HEAVY_CLASS_COMPLIANCE', 'Heavy-class compliance'), ('ASSOCIATION', 'Vehicle / operator association'), ('BASE', 'Operating base'), ('DOCUMENT', 'Supporting document'), ('HISTORY', 'Platform history')], max_length=32)),
                ('state', models.CharField(choices=[('NOT_SUBMITTED', 'Not submitted'), ('SUBMITTED', 'Submitted'), ('IN_REVIEW', 'In review'), ('INFO_REQUESTED', 'More info requested'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_SUBMITTED', max_length=16)),
                ('issuing_authority', models.CharField(blank=True, default='', max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='verification.verificationdecision')),
                ('owner_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='operators.operatingbase')),
                ('subject_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='operators.operatorprofile')),
                ('subject_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'verification_record',
            },
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('SELFIE', 'Selfie / photo'), ('DRIVING_LICENCE', 'Driving licence'), ('GOOD_CONDUCT_CERT', 'Certificate of Good Conduct'), ('LOGBOOK', 'Logbook / registration'), ('INSPECTION_CERT', 'Inspection certificate'), ('INSURANCE_CERT', 'Insurance certificate'), ('NTSA_OPERATOR_LICENCE', 'NTSA commercial operator licence'), ('SPEED_LIMITER_CERT', 'Speed-limiter certificate'), ('TELEMATICS_CERT', 'Telematics certificate'), ('OWNER_CONSENT', 'Owner consent (authorised driver)'), ('VEHICLE_PHOTO', 'Vehicle photo'), ('PLATE_PHOTO', 'Number-plate photo'), ('BASE_PHOTO', 'Operating-location photo'), ('OTHER', 'Other document')], max_length=32)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='evidence.evidenceobject')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='verification.verificationrecord')),
            ],
            options={
                'db_table': 'verification_evidence',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='verificationdecision',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='verification.verificationrecord'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['state'], name='verificatio_state_e01980_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['subject_type', 'domain', 'state'], name='verificatio_subject_1f547e_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['expires_at'], name='verificatio_expires_fe4d50_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject_base__isnull', True), ('subject_operator__isnull', False), ('subject_vehicle__isnull', True)), models.Q(('subject_base__isnull', True), ('subject_operator__isnull', True), ('subject_vehicle__isnull', False)), models.Q(('subject_base__isnull', False), ('subject_operator__isnull', True), ('subject_vehicle__isnull', True)), _connector='OR'), name='verification_record_exactly_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='verificationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_operator__isnull', False)), fields=('subject_operator', 'domain'), name='uniq_operator_domain'),
        ),
        migrations.AddConstraint(
            model_name='verificationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_vehicle__isnull', False)), fields=('subject_vehicle', 'domain'), name='uniq_vehicle_domain'),
        ),
        migrations.AddConstraint(
            model_name='verificationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_base__isnull', False)), fields=('subject_base', 'domain'), name='uniq_base_domain'),
        ),
        migrations.AddIndex(
            model_name='verificationevidence',
            index=models.Index(fields=['record', 'superseded_at'], name='verificatio_record__be1475_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdecision',
            index=models.Index(fields=['record', 'created_at'], name='verificatio_record__c93460_idx'),
        ),
    ]
