# Generated by Django 5.2.17 on 2026-09-08 18:42

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfigVersion',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version', models.PositiveIntegerField(editable=False, unique=True)),
                ('rationale', models.TextField()),
                ('snapshot', models.JSONField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='config_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_config_version',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_config.platformconfigversion')),
            ],
            options={
                'db_table': 'platform_config',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='platform_config_singleton')],
            },
        ),
    ]
