# Generated by Django 5.2.17 on 2026-09-09 09:10

import fikisha.common.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_config', '0003_seed_pilot_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name_en', models.CharField(max_length=80)),
                ('name_sw', models.CharField(max_length=80)),
                ('heavy', models.BooleanField(default=False, help_text='Requires HEAVY_CLASS_COMPLIANCE verification.')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'config_vehicle_class',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
