# Generated by Django 5.2.17 on 2026-09-09 06:56

import django.contrib.postgres.fields
import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('platform_config', '0002_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingBase',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('STAGE', 'Stage'), ('BASE', 'Base'), ('YARD', 'Yard'), ('WAITING_AREA', 'Waiting area')], max_length=16)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('landmark', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='platform_config.zone')),
            ],
            options={
                'db_table': 'operating_base',
            },
        ),
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Additional contact numbers; the login phone lives on User.', size=None)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended'), ('OFFBOARDED', 'Offboarded')], default='PENDING', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_profile',
            },
        ),
        migrations.CreateModel(
            name='BaseMembership',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, default='', help_text='Free text (e.g. owner / member): a claim of presence, not formal ownership.', max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_memberships', to='groups.operatorgroup')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='operators.operatingbase')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_memberships', to='operators.operatorprofile')),
            ],
            options={
                'db_table': 'base_membership',
            },
        ),
        migrations.AddIndex(
            model_name='operatingbase',
            index=models.Index(fields=['type'], name='operating_b_type_79cb56_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingbase',
            index=models.Index(fields=['zone'], name='operating_b_zone_id_3c19ad_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorprofile',
            index=models.Index(fields=['status'], name='operator_pr_status_09a812_idx'),
        ),
        migrations.AddIndex(
            model_name='basemembership',
            index=models.Index(fields=['base', 'status'], name='base_member_base_id_f9f152_idx'),
        ),
        migrations.AddConstraint(
            model_name='basemembership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('operator__isnull', False)), models.Q(('group__isnull', False), ('operator__isnull', True)), _connector='OR'), name='base_membership_exactly_one_party'),
        ),
        migrations.AddConstraint(
            model_name='basemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('operator__isnull', False)), fields=('base', 'operator'), name='uniq_base_operator'),
        ),
        migrations.AddConstraint(
            model_name='basemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('base', 'group'), name='uniq_base_group'),
        ),
    ]
