# Generated by Django 5.2.17 on 2026-09-11 08:53

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0002_alter_evidenceobject_purpose_and_more'),
        ('jobs', '0005_recipient_reported_issue_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('AMICABLE_PENDING', 'Amicable resolution pending'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=16)),
                ('pre_dispute_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('NEGOTIATING', 'Negotiating'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('AT_PICKUP', 'At pickup'), ('PICKED_UP', 'Picked up'), ('IN_TRANSIT', 'In transit'), ('AT_DESTINATION', 'At destination'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed')], max_length=16)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='jobs.job')),
                ('officer_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opened_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('MISSING_GOODS', 'Missing goods (partial shortage)'), ('WRONG_RECIPIENT', 'Wrong recipient'), ('WRONG_PICKUP', 'Wrong pickup'), ('MISCONDUCT', 'Misconduct'), ('BREAKDOWN', 'Breakdown'), ('ACCIDENT', 'Accident'), ('DELAY', 'Delay'), ('CANCELLATION', 'Cancellation'), ('OTHER', 'Other')], max_length=20)),
                ('other_label', models.CharField(blank=True, default='', max_length=120)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=8)),
                ('reported_by_kind', models.CharField(choices=[('USER', 'Platform user'), ('RECIPIENT_LINK', 'Recipient (scoped link)'), ('ADMIN', 'Administrator')], max_length=16)),
                ('reported_by_link_id', models.UUIDField(blank=True, null=True)),
                ('source_report_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under review'), ('AMICABLE_PENDING', 'Amicable resolution pending'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=16)),
                ('linked_custody_event_ids', models.JSONField(blank=True, default=list)),
                ('sla_ack_due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_action_due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='jobs.job')),
                ('owner_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reported_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField()),
                ('escalated_to', models.CharField(max_length=120)),
                ('advised_external_options', models.BooleanField(default=False)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='incidents.dispute')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='incidents.incident')),
            ],
            options={
                'db_table': 'escalation',
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by_kind', models.CharField(choices=[('BUSINESS', 'Business'), ('OPERATOR', 'Operator'), ('GROUP', 'Operator group'), ('RECIPIENT', 'Recipient'), ('ADMIN', 'Administrator')], max_length=16)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('evidence_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='evidence.evidenceobject')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='incidents.incident')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_evidence',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatement',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('party_kind', models.CharField(choices=[('BUSINESS', 'Business'), ('OPERATOR', 'Operator'), ('GROUP', 'Operator group'), ('RECIPIENT', 'Recipient'), ('ADMIN', 'Administrator')], max_length=16)),
                ('text', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='incidents.incident')),
                ('party_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_statement',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('outcome_code', models.CharField(choices=[('AMICABLE_AGREEMENT', 'Amicable agreement'), ('ADMIN_DETERMINATION', 'Administrative determination'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('rationale', models.TextField()),
                ('commission_treatment', models.CharField(choices=[('APPLY', 'Apply as normal'), ('REDUCE', 'Reduce'), ('WAIVE', 'Waive')], default='APPLY', max_length=8)),
                ('reduced_amount_kes', models.BigIntegerField(blank=True, null=True)),
                ('agreed_compensation_kes', models.BigIntegerField(blank=True, null=True)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('routed_job_status', models.CharField(choices=[('DRAFT', 'Draft'), ('REQUESTED', 'Requested'), ('NEGOTIATING', 'Negotiating'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('AT_PICKUP', 'At pickup'), ('PICKED_UP', 'Picked up'), ('IN_TRANSIT', 'In transit'), ('AT_DESTINATION', 'At destination'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed')], max_length=16)),
                ('resolved_by_is_platform_admin', models.BooleanField(default=False)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='incidents.dispute')),
                ('resolved_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resolution',
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['job', 'status'], name='ix_dispute_job_status'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['OPEN', 'UNDER_REVIEW', 'AMICABLE_PENDING', 'ESCALATED'])), fields=('job',), name='uq_dispute_one_open_per_job'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['job', 'status'], name='ix_incident_job_status'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(condition=models.Q(('status__in', ['OPEN', 'UNDER_REVIEW', 'AMICABLE_PENDING'])), fields=['status'], name='ix_incident_open'),
        ),
        migrations.AddIndex(
            model_name='incidentevidence',
            index=models.Index(fields=['incident', 'created_at'], name='incident_ev_inciden_5cb0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentstatement',
            index=models.Index(fields=['incident', 'created_at'], name='incident_st_inciden_f1f7c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='resolution',
            constraint=models.CheckConstraint(condition=models.Q(('routed_job_status__in', ['CANCELLED', 'COMPLETED', 'FAILED'])), name='ck_resolution_routed_status_no_resume'),
        ),
        migrations.AddConstraint(
            model_name='resolution',
            constraint=models.CheckConstraint(condition=models.Q(('reduced_amount_kes__isnull', True), ('reduced_amount_kes__gte', 0), _connector='OR'), name='ck_resolution_reduced_amount_non_negative'),
        ),
    ]
