# Generated by Django 5.2.17 on 2026-09-10 16:23

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('jobs', '0002_lifecycle_backstop'),
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationThread',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator_party', models.CharField(choices=[('OPERATOR', 'Individual operator'), ('GROUP', 'Operator group')], max_length=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUPERSEDED', 'Superseded'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='groups.operatorgroup')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negotiation_threads', to='jobs.job')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operators.operatorprofile')),
            ],
            options={
                'db_table': 'negotiation_thread',
            },
        ),
        migrations.CreateModel(
            name='NegotiationEntry',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_role', models.CharField(choices=[('BUSINESS', 'Business'), ('OPERATOR', 'Operator'), ('ADMIN', 'Administrator')], max_length=12)),
                ('type', models.CharField(choices=[('PROPOSE', 'Propose'), ('COUNTER', 'Counter-offer'), ('ACCEPT', 'Accept'), ('REJECT', 'Reject')], max_length=12)),
                ('amount_kes', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('note', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('in_response_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='negotiation.negotiationentry')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negotiation_entries', to='jobs.job')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='negotiation.negotiationthread')),
            ],
            options={
                'db_table': 'negotiation_entry',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='negotiationthread',
            index=models.Index(fields=['job', 'status'], name='ix_negotiation_thread_job'),
        ),
        migrations.AddConstraint(
            model_name='negotiationthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', True), ('operator__isnull', False)), models.Q(('group__isnull', False), ('operator__isnull', True)), _connector='OR'), name='ck_negotiation_thread_one_party'),
        ),
        migrations.AddConstraint(
            model_name='negotiationthread',
            constraint=models.UniqueConstraint(condition=models.Q(('operator__isnull', False)), fields=('job', 'operator'), name='uq_negotiation_thread_operator'),
        ),
        migrations.AddConstraint(
            model_name='negotiationthread',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('job', 'group'), name='uq_negotiation_thread_group'),
        ),
        migrations.AddIndex(
            model_name='negotiationentry',
            index=models.Index(fields=['thread', 'created_at'], name='ix_negotiation_entry_thread'),
        ),
        migrations.AddIndex(
            model_name='negotiationentry',
            index=models.Index(fields=['job'], name='ix_negotiation_entry_job'),
        ),
        migrations.AddConstraint(
            model_name='negotiationentry',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'REJECT'), ('amount_kes__isnull', False), _connector='OR'), name='ck_negotiation_entry_amount_required'),
        ),
        migrations.AddConstraint(
            model_name='negotiationentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kes__isnull', True), ('amount_kes__gt', 0), _connector='OR'), name='ck_negotiation_entry_amount_positive'),
        ),
    ]
