# Generated by Django 5.2.17 on 2026-09-15 06:26

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiation', '0002_append_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negotiationentry',
            options={'ordering': ['seq']},
        ),
        # Phase 2D final-verification finding (2026-09-11): `_entries()`
        # ordered by `(created_at, id)`, but two entries written back-to-back
        # can tie on `created_at` (auto_now_add's clock resolution) and the
        # UUIDv7 `id` is only time-ordered at millisecond granularity. `seq`
        # is a real Postgres sequence — strictly monotonic under both.
        migrations.RunSQL(
            sql="CREATE SEQUENCE negotiation_entry_seq;",
            reverse_sql="DROP SEQUENCE negotiation_entry_seq;",
        ),
        migrations.AddField(
            model_name='negotiationentry',
            name='seq',
            field=models.BigIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('negotiation_entry_seq')", []), editable=False, unique=True),
        ),
        migrations.RunSQL(
            sql="ALTER SEQUENCE negotiation_entry_seq OWNED BY negotiation_entry.seq;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
