# Generated by Django 5.2.17 on 2026-09-08 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('DEAD', 'Dead-lettered')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Next attempt time')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_event',
                'ordering': ['id'],
                'indexes': [models.Index(condition=models.Q(('status', 'PENDING')), fields=['status', 'available_at', 'id'], name='outbox_pending_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_even_aggrega_196f8a_idx')],
            },
        ),
    ]
