# Generated by Django 5.2.17 on 2026-09-09 12:21

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceObject',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=300, unique=True)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('pii_class', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=8)),
                ('purpose', models.CharField(choices=[('VERIFICATION_DOC', 'Verification document'), ('VEHICLE_PHOTO', 'Vehicle photo'), ('PROFILE_PHOTO', 'Profile photo'), ('BASE_PHOTO', 'Operating-location photo')], max_length=32)),
                ('linked_entity_type', models.CharField(blank=True, default='', max_length=60)),
                ('linked_entity_id', models.UUIDField(blank=True, null=True)),
                ('uploaded_by_kind', models.CharField(choices=[('OPERATOR', 'Operator'), ('BUSINESS', 'Business user'), ('ADMIN', 'Administrator'), ('SYSTEM', 'System')], default='OPERATOR', max_length=12)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_object',
            },
        ),
        migrations.CreateModel(
            name='EvidenceAccessLog',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accessed_by_role', models.CharField(blank=True, default='', max_length=40)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='evidence.evidenceobject')),
            ],
            options={
                'db_table': 'evidence_access_log',
            },
        ),
        migrations.AddIndex(
            model_name='evidenceobject',
            index=models.Index(fields=['linked_entity_type', 'linked_entity_id'], name='evidence_ob_linked__4cc0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceobject',
            index=models.Index(fields=['purpose'], name='evidence_ob_purpose_63cd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceaccesslog',
            index=models.Index(fields=['evidence_object', 'created_at'], name='evidence_ac_evidenc_fba6e9_idx'),
        ),
    ]
