# Generated by Django 5.2.17 on 2026-09-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceobject',
            name='purpose',
            field=models.CharField(choices=[('VERIFICATION_DOC', 'Verification document'), ('VEHICLE_PHOTO', 'Vehicle photo'), ('PROFILE_PHOTO', 'Profile photo'), ('BASE_PHOTO', 'Operating-location photo'), ('INCIDENT_EVIDENCE', 'Incident evidence')], max_length=32),
        ),
        migrations.AlterField(
            model_name='evidenceobject',
            name='uploaded_by_kind',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('BUSINESS', 'Business user'), ('ADMIN', 'Administrator'), ('SYSTEM', 'System'), ('RECIPIENT', 'Recipient')], default='OPERATOR', max_length=12),
        ),
    ]
