# Generated by Django 5.2.17 on 2026-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_evidenceobject_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceobject',
            name='purpose',
            field=models.CharField(choices=[('VERIFICATION_DOC', 'Verification document'), ('VEHICLE_PHOTO', 'Vehicle photo'), ('PROFILE_PHOTO', 'Profile photo'), ('BASE_PHOTO', 'Operating-location photo'), ('INCIDENT_EVIDENCE', 'Incident evidence'), ('CUSTODY_PROOF', 'Pickup/delivery proof photo')], max_length=32),
        ),
    ]
