# Generated by Django 5.2.17 on 2026-09-08 18:42

import django.utils.timezone
import fikisha.common.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('seq', models.BigIntegerField(editable=False, unique=True)),
                ('actor_role', models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('BUSINESS', 'Business'), ('OPERATOR', 'Operator'), ('GROUP_MANAGER', 'Group manager'), ('GROUP_DRIVER', 'Group driver'), ('RECIPIENT', 'Recipient'), ('OPERATIONS_OFFICER', 'Operations Officer'), ('PLATFORM_ADMIN', 'Platform Admin'), ('SYSTEM', 'System')], max_length=32)),
                ('action', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('server_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('request_id', models.CharField(blank=True, default='-', max_length=128)),
                ('source_channel', models.CharField(choices=[('API', 'API'), ('ADMIN_UI', 'Admin UI'), ('WEBHOOK', 'Webhook'), ('SCHEDULER', 'Scheduler'), ('CLI', 'CLI / management command')], default='API', max_length=16)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_device', models.CharField(blank=True, max_length=256, null=True)),
                ('prev_hash', models.CharField(blank=True, default='', max_length=64)),
                ('row_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'db_table': 'audit_log_entry',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='AuditChainHead',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_seq', models.BigIntegerField(default=0)),
                ('last_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audit_chain_head',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='audit_chain_head_singleton')],
            },
        ),
    ]
