# Generated by Django 5.2.17 on 2026-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_append_only_db_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='actor_role',
            field=models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('USER', 'Authenticated user'), ('BUSINESS', 'Business'), ('OPERATOR', 'Operator'), ('GROUP_MANAGER', 'Group manager'), ('GROUP_DRIVER', 'Group driver'), ('RECIPIENT', 'Recipient'), ('OPERATIONS_OFFICER', 'Operations Officer'), ('PLATFORM_ADMIN', 'Platform Admin'), ('SYSTEM', 'System')], max_length=32),
        ),
    ]
