# Generated by Django 5.2.17 on 2026-09-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_lifecycle_backstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientotpchallenge',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='otp_challenges', to='jobs.recipientaccesslink'),
        ),
    ]
