# Generated by Django 5.2.17 on 2026-09-11 07:24

import django.db.models.deletion
import fikisha.common.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_recipientotpchallenge_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientReportedIssue',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reported_via_link_id', models.UUIDField()),
                ('category', models.CharField(choices=[('WRONG_RECIPIENT', 'Wrong recipient'), ('DAMAGE', 'Damage'), ('MISSING_GOODS', 'Missing goods'), ('WRONG_GOODS', 'Wrong goods'), ('OTHER', 'Other')], max_length=20)),
                ('other_label', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('photo_evidence_ids', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_issues', to='jobs.job')),
            ],
            options={
                'db_table': 'recipient_reported_issue',
                'indexes': [models.Index(fields=['job', 'created_at'], name='ix_recipient_issue_job')],
            },
        ),
    ]
