# Generated by Django 5.2.17 on 2026-09-11 10:01

import django.db.models.deletion
import fikisha.common.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_recipient_reported_issue_append_only'),
        ('platform_config', '0005_seed_vehicle_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agreed_price_kes', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('min_fee_kes', models.BigIntegerField()),
                ('cap_kes', models.BigIntegerField()),
                ('commission_kes', models.BigIntegerField()),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='jobs.agreement')),
                ('config_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_config.platformconfigversion')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission_record', to='jobs.job')),
            ],
            options={
                'db_table': 'commission_record',
            },
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.UUIDField(default=fikisha.common.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('REDUCTION', 'Partial reduction'), ('WAIVER', 'Full waiver')], max_length=12)),
                ('amount_kes', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('authorized_by_is_platform_admin', models.BooleanField(default=False)),
                ('source_dispute_id', models.UUIDField(blank=True, null=True)),
                ('source_resolution_id', models.UUIDField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('config_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_config.platformconfigversion')),
                ('commission_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='jobs.commissionrecord')),
            ],
            options={
                'db_table': 'commission_adjustment',
            },
        ),
        migrations.AddConstraint(
            model_name='commissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('agreed_price_kes__gte', 0)), name='ck_commission_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='commissionrecord',
            constraint=models.CheckConstraint(condition=models.Q(('commission_kes__gte', 0)), name='ck_commission_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='commissionadjustment',
            index=models.Index(fields=['commission_record', 'created_at'], name='commission__commiss_0c26ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='commissionadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kes__lt', 0)), name='ck_commission_adjustment_negative'),
        ),
    ]
