# Generated by Django 5.2.17 on 2026-09-15 06:26

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_commission_append_only'),
    ]

    operations = [
        # Phase 2D final-verification finding (2026-09-11): `verify_otp()`
        # picked "the newest challenge" via `-created_at` alone, which can tie
        # under `auto_now_add`'s clock resolution. `seq` is a real Postgres
        # sequence — strictly monotonic, unlike `created_at` or the UUIDv7 id.
        migrations.RunSQL(
            sql="CREATE SEQUENCE pickup_otp_challenge_seq;",
            reverse_sql="DROP SEQUENCE pickup_otp_challenge_seq;",
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE recipient_otp_challenge_seq;",
            reverse_sql="DROP SEQUENCE recipient_otp_challenge_seq;",
        ),
        migrations.AddField(
            model_name='pickupotpchallenge',
            name='seq',
            field=models.BigIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('pickup_otp_challenge_seq')", []), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='recipientotpchallenge',
            name='seq',
            field=models.BigIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('recipient_otp_challenge_seq')", []), editable=False, unique=True),
        ),
        # Ownership: the sequence is dropped automatically if the column is
        # ever dropped (Postgres hygiene; has no effect on `nextval()` behaviour).
        migrations.RunSQL(
            sql="ALTER SEQUENCE pickup_otp_challenge_seq OWNED BY pickup_otp_challenge.seq;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER SEQUENCE recipient_otp_challenge_seq OWNED BY recipient_otp_challenge.seq;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
